### ISSUE TITLE
Vertical center in activity_main

### ISSUE THREAD

**Issue by setetiq** [udacity/andfun-kotlin-dice-roller#4]
It should be used "gravity" parameter in LinearLayout "central_vertical" instead of layout_gravity.
In other case it will be displayed in top of the view.

Android Studio 3.6.2
Build #AI-192.7142.36.36.6308749, built on March 18, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: org.jetbrains.kotlin, com.google.services.firebase

**Comment by SudKul** [comment]
For new learners:
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
