### ISSUE TITLE
Issues compiling branches on newly installed android studio

### ISSUE THREAD

**Issue by assafmendelson** [udacity/andfun-kotlin-dice-roller#6]
When opening the project most examples do not compile and require configuration:
1. when opening, the SDK requires accepting licenses and downloading and installing multiple packages (compared to creating a new project as described in the course).
2. even when downloading and updating everything, one needs to add android.useAndroidX=true to gradle.properties for compilation to work.

**Comment by SudKul** [comment]
We have recently upgraded the repo to AndoirdX in this [commit](https://github.com/udacity/andfun-kotlin-dice-roller/commit/827bf70e73bc6983bb7f9af74b520d0f38f8935e). Hopefully, it will resolve the issue for new learners.
